---
language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=1.4
  - ANSIBLE_VERSION=1.5
  - ANSIBLE_VERSION=1.6
  - ANSIBLE_VERSION=1.7
  - ANSIBLE_VERSION=1.8

before_install:
  - sudo apt-get update -qq

  # Remove lxc-docker
  - sudo apt-get remove --purge lxc-docker || true

install:
  # Install Ansible.
  - pip install ansible==$ANSIBLE_VERSION

  # Add ansible.cfg to pick up roles path.
  - printf "[defaults]\nroles_path = ../" > ansible.cfg

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

notifications:
  email: false
