---
# handlers file for docker
- name: Start Docker
  service: name=docker state=started

- name: Reload docker
  service: name=docker state=reloaded

- name: Restart docker io
  service: name=docker.io state=restarted

